[tool.ruff]
# Set the maximum line length to 100.
line-length = 100

[project]
# Support Python 3.12+.
requires-python = ">=3.12"
name = "pseudospectral"
version = "0.1.0"

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]
