[project]
name = "pseudospectral"
version = "0.1.0"
license = "GNU General Public License v3.0"
authors = [
    {name = "Mayank Goel", email = "mayank.goel447@gmail.com"},
    {name = "Julian Lenz", email = "j.lenz@hzdr.de"}
]
description = "A Python package for pseudospectral discretization of the Dirac operator."
keywords = ["pseudospectral", "spectral methods", "Dirac Operator"]
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "numpy==2.0.0",
    "scipy==1.14.0",
    "matplotlib==3.9.0",
]
