name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        cache: 'pip' # caching pip dependencies        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .   
    - name: Build the package
      run: |
        pip install build
        python -m build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: dist/*

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: python-package
        path: dist
    - name: Install built package
      run: |
        python -m pip install --upgrade pip
        pip install dist/*.whl
    - name: Test with pytest
      run: |
        pytest .
